### ISSUE TITLE
_ncs.error.Error: 'unknown namespace: in openconfig'

### ISSUE THREAD

**Issue by ygorelik** [model-driven-devops/nso-oc-services#150]
When XE discovered openconfig service system is applied, getting 'unknown namespace: in openconfig' error:
```
/Users/ygorelik/nso-venv/bin/python3 /Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py
Discovered openconfig service 'system':
{
  "mdd:openconfig": {
    "openconfig-system:system": {
      "openconfig-system:aaa": {
        "openconfig-system:server-groups": {
          "openconfig-system:server-group": []
        },
        "openconfig-system:accounting": {},
        "openconfig-system:authorization": {},
        "openconfig-system:authentication": {}
      },
      "openconfig-system:clock": {},
      "openconfig-system:config": {},
      "openconfig-system:dns": {},
      "openconfig-system:logging": {},
      "openconfig-system:ntp": {
        "openconfig-system:config": {},
        "openconfig-system:ntp-keys": {
          "openconfig-system:ntp-key": []
        },
        "openconfig-system:servers": {
          "openconfig-system:server": []
        }
      },
      "openconfig-system:ssh-server": {
        "openconfig-system:config": {
          "openconfig-system:protocol-version": "V1_V2"
        },
        "openconfig-system-ext:algorithm": {
          "openconfig-system-ext:config": {}
        }
      },
      "openconfig-system-ext:services": {
        "openconfig-system-ext:http": {
          "openconfig-system-ext:config": {
            "openconfig-system-ext:http-enabled": false
          }
        },
        "openconfig-system-ext:config": {
          "openconfig-system-ext:ip-domain-lookup": true,
          "openconfig-system-ext:archive-logging": false,
          "openconfig-system-ext:ip-bootp-server": true,
          "openconfig-system-ext:ip-dns-server": false,
          "openconfig-system-ext:ip-identd": false,
          "openconfig-system-ext:ip-rcmd-rcp-enable": false,
          "openconfig-system-ext:ip-rcmd-rsh-enable": false,
          "openconfig-system-ext:finger": true,
          "openconfig-system-ext:service-config": false,
          "openconfig-system-ext:service-tcp-small-servers": false,
          "openconfig-system-ext:service-udp-small-servers": false,
          "openconfig-system-ext:service-pad": true,
          "openconfig-system-ext:service-password-encryption": false
        },
        "openconfig-system-ext:login-security-policy": {
          "openconfig-system-ext:config": {
            "openconfig-system-ext:on-success": false,
            "openconfig-system-ext:on-failure": false
          },
          "openconfig-system-ext:block-for": {
            "openconfig-system-ext:config": {}
          }
        },
        "openconfig-system-ext:boot-network": {
          "openconfig-system-ext:config": {
            "openconfig-system-ext:bootnetwork-enabled": "DISABLED"
          }
        }
      }
    }
  }
}

Not translated NSO configuration:
{
  "devices": {
    "device": [
      {
        "name": "ios",
        "config": {}
      }
    ]
  }
}

Applying commit dry-run to discovered system OC service:
Traceback (most recent call last):
  File "/Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py", line 271, in <module>
    result = apply_service(dev_name, oc_cfg, "dry-run")
  File "/Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py", line 101, in apply_service
    _ncs.maapi.load_config_cmds(m.msock, t.th,
_ncs.error.Error: external error (19): Error on line 0: unknown namespace:  in openconfig
```
The XE device config is attached:
```
{
  "data": {
    "tailf-ncs:devices": {
      "device": [
        {
          "name": "ios",
          "config": {
            "ietf-yang-library:yang-library": {
              "module-set": [
                {
                  "name": "common",
                  "module": [
                    {
                      "name": "ietf-interfaces",
                      "revision": "2014-05-08",
                      "namespace": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
                      "feature": ["arbitrary-names", "if-mib", "pre-provisioning"]
                    },
                    {
                      "name": "ietf-ip",
                      "revision": "2014-06-16",
                      "namespace": "urn:ietf:params:xml:ns:yang:ietf-ip",
                      "feature": ["ipv4-non-contiguous-netmasks", "ipv6-privacy-autoconf"]
                    },
                    {
                      "name": "tailf-ned-cisco-ios",
                      "revision": "2022-04-29",
                      "namespace": "urn:ios"
                    },
                    {
                      "name": "tailf-ned-cisco-ios-stats",
                      "namespace": "urn:ios-stats"
                    }
                  ],
                  "import-only-module": [
                    {
                      "name": "cliparser-extensions-v11",
                      "revision": "",
                      "namespace": "http://tail-f.com/ned/cliparser_v11"
                    },
                    {
                      "name": "tailf-ned-cisco-ios-id",
                      "revision": "",
                      "namespace": "urn:ios-id"
                    }
                  ]
                }
              ],
              "schema": [
                {
                  "name": "common",
                  "module-set": ["common"]
                }
              ],
              "datastore": [
                {
                  "name": "ds:running",
                  "schema": "common"
                },
                {
                  "name": "ds:intended",
                  "schema": "common"
                },
                {
                  "name": "ds:operational",
                  "schema": "common"
                }
              ],
              "content-id": "c41198350a159b7f7e56ecdd1ebaed6b"
            },
            "ietf-yang-library:modules-state": {
              "module-set-id": "c41198350a159b7f7e56ecdd1ebaed6b",
              "module": [
                {
                  "name": "cliparser-extensions-v11",
                  "revision": "",
                  "namespace": "http://tail-f.com/ned/cliparser_v11",
                  "conformance-type": "import"
                },
                {
                  "name": "ietf-interfaces",
                  "revision": "2014-05-08",
                  "namespace": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
                  "feature": ["arbitrary-names", "if-mib", "pre-provisioning"],
                  "conformance-type": "implement"
                },
                {
                  "name": "ietf-ip",
                  "revision": "2014-06-16",
                  "namespace": "urn:ietf:params:xml:ns:yang:ietf-ip",
                  "feature": ["ipv4-non-contiguous-netmasks", "ipv6-privacy-autoconf"],
                  "conformance-type": "implement"
                },
                {
                  "name": "tailf-ned-cisco-ios",
                  "revision": "2022-04-29",
                  "namespace": "urn:ios",
                  "conformance-type": "implement"
                },
                {
                  "name": "tailf-ned-cisco-ios-id",
                  "revision": "",
                  "namespace": "urn:ios-id",
                  "conformance-type": "import"
                },
                {
                  "name": "tailf-ned-cisco-ios-stats",
                  "revision": "",
                  "namespace": "urn:ios-stats",
                  "conformance-type": "implement"
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

The issue appeared after merging pull request #149.

**Comment by ygorelik** [comment]
Similar error appears when applying network-instance service:
```
/Users/ygorelik/nso-venv/bin/python3 /Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py
Discovered openconfig service 'network-instance':
{
  "mdd:openconfig": {
    "openconfig-network-instance:network-instances": {
      "openconfig-network-instance:network-instance": [
        {
          "openconfig-network-instance:name": "default",
          "openconfig-network-instance:config": {
            "openconfig-network-instance:name": "default",
            "openconfig-network-instance:type": "DEFAULT_INSTANCE",
            "openconfig-network-instance:enabled": "true"
          },
          "openconfig-network-instance:protocols": {
            "openconfig-network-instance:protocol": [
              {
                "openconfig-network-instance:identifier": "STATIC",
                "openconfig-network-instance:name": "DEFAULT",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:identifier": "STATIC",
                  "openconfig-network-instance:name": "DEFAULT"
                },
                "openconfig-network-instance:static-routes": {
                  "openconfig-network-instance:static": []
                }
              }
            ]
          },
          "openconfig-network-instance:interfaces": {
            "openconfig-network-instance:interface": [
              {
                "openconfig-network-instance:id": "Loopback0",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:id": "Loopback0",
                  "openconfig-network-instance:interface": "Loopback0",
                  "openconfig-network-instance:subinterface": "0"
                }
              },
              {
                "openconfig-network-instance:id": "GigabitEthernet0/0.111",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:id": "GigabitEthernet0/0.111",
                  "openconfig-network-instance:interface": "GigabitEthernet0/0",
                  "openconfig-network-instance:subinterface": "111"
                }
              },
              {
                "openconfig-network-instance:id": "GigabitEthernet0/1.112",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:id": "GigabitEthernet0/1.112",
                  "openconfig-network-instance:interface": "GigabitEthernet0/1",
                  "openconfig-network-instance:subinterface": "112"
                }
              }
            ]
          },
          "openconfig-network-instance:vlan": []
        }
      ]
    }
  }
}

Not translated NSO configuration:
{
  "devices": {
    "device": [
      {
        "name": "ios",
        "config": {
          "tailf-ned-cisco-ios:interface": {
            "GigabitEthernet": [
              {
                "name": "0/0.111",
                "encapsulation": {
                  "dot1Q": {
                    "vlan-id": 111
                  }
                },
                "service-policy": {
                  "output": "ford"
                }
              },
              {
                "name": "0/1.112",
                "encapsulation": {
                  "dot1Q": {
                    "vlan-id": 112
                  }
                },
                "service-policy": {
                  "output": "volvo"
                }
              }
            ]
          }
        }
      }
    ]
  }
}

Applying commit dry-run to discovered network-instance OC service:
Traceback (most recent call last):
  File "/Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py", line 271, in <module>
    result = apply_service(dev_name, oc_cfg, "dry-run")
  File "/Users/ygorelik/nso-oc-services/oc-service-dicovery/python/actions/discover_oc_service.py", line 101, in apply_service
    _ncs.maapi.load_config_cmds(m.msock, t.th,
_ncs.error.Error: external error (19): Error on line 0: unknown namespace:  in openconfig


Process finished with exit code 1
```

**Comment by ygorelik** [comment]
Could not reproduce this errors after recompiling mdd models. Hence closing the issue.
