### ISSUE TITLE
Bad key "None" ("None" is not a valid value.) at: /devices/device/config/router/bgp

### ISSUE THREAD

**Issue by ygorelik** [model-driven-devops/nso-oc-services#176]
When applying below network-instance config (BGP is not configured on the router), I am getting this Python error:
```
<INFO> 07-Mar-2023::13:05:58.978 mdd ncs-dp-59389-mdd:main:0-3-th-23120: - xe-65 BGP global
<ERROR> 07-Mar-2023::13:05:58.979 mdd ncs-dp-59389-mdd:main:0-3-th-23120: - badly formatted or nonexistent path (8): Bad key "None" ("None" is not a valid value.) at: /devices/device/config/router/bgp
<ERROR> 07-Mar-2023::13:05:58.980 mdd ncs-dp-59389-mdd:main:0-3-th-23120: - Traceback (most recent call last):
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/application.py", line 766, in wrapper
    pl = fn(self, tctx, root, service, proplist)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/main.py", line 30, in cb_create
    check_xe_features(self)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_main.py", line 39, in check_xe_features
    xe_network_instances_program_service(oc_self)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_network_instances.py", line 32, in xe_network_instances_program_service
    xe_configure_protocols(self, service_table_connection_dict, instance_bgp_list)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_network_instances.py", line 367, in xe_configure_protocols
    xe_bgp_global_program_service(self, bgp_instance[0], bgp_instance[1], bgp_instance[2])
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_bgp.py", line 13, in xe_bgp_global_program_service
    if not self.root.devices.device[self.device_name].config.ios__router.bgp.exists(
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maagic.py", line 1260, in exists
    return self._backend._exists(self._path + keystr)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maagic.py", line 135, in _exists
    return self.exists(path)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maapi.py", line 1733, in proxy
    return real(self2.maapi, self2.th, *args, **kwargs)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maapi.py", line 548, in exists
    return True if _tm.maapi.exists(self.msock, th, path) else False
_ncs.error.Error: badly formatted or nonexistent path (8): Bad key "None" ("None" is not a valid value.) at: /devices/device/config/router/bgp
```

Network-instance config discovered via translation from device config to OC service:
```
{
  "mdd:openconfig": {
    "openconfig-network-instance:network-instances": {
      "openconfig-network-instance:network-instance": [
        {
          "openconfig-network-instance:name": "default",
          "openconfig-network-instance:config": {
            "openconfig-network-instance:name": "default",
            "openconfig-network-instance:type": "DEFAULT_INSTANCE",
            "openconfig-network-instance:enabled": "true"
          },
          "openconfig-network-instance:protocols": {
            "openconfig-network-instance:protocol": [
              {
                "openconfig-network-instance:identifier": "STATIC",
                "openconfig-network-instance:name": "DEFAULT",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:identifier": "STATIC",
                  "openconfig-network-instance:name": "DEFAULT"
                },
                "openconfig-network-instance:static-routes": {
                  "openconfig-network-instance:static": [
                    {
                      "openconfig-network-instance:prefix": "0.0.0.0/0",
                      "openconfig-network-instance:config": {
                        "openconfig-network-instance:prefix": "0.0.0.0/0"
                      },
                      "openconfig-network-instance:next-hops": {
                        "openconfig-network-instance:next-hop": [
                          {
                            "openconfig-network-instance:index": "172.23.80.1",
                            "openconfig-network-instance:config": {
                              "openconfig-network-instance:index": "172.23.80.1",
                              "openconfig-network-instance:next-hop": "172.23.80.1"
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              },
              {
                "openconfig-network-instance:identifier": "BGP",
                "openconfig-network-instance:name": "BGP",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:identifier": "BGP",
                  "openconfig-network-instance:name": "BGP",
                  "openconfig-network-instance:enabled": false
                },
                "openconfig-network-instance:bgp": {
                  "openconfig-network-instance:peer-groups": {
                    "openconfig-network-instance:peer-group": []
                  },
                  "openconfig-network-instance:neighbors": {
                    "openconfig-network-instance:neighbor": []
                  }
                }
              }
            ]
          },
          "openconfig-network-instance:interfaces": {
            "openconfig-network-instance:interface": [
              {
                "openconfig-network-instance:id": "GigabitEthernet2",
                "openconfig-network-instance:config": {
                  "openconfig-network-instance:id": "GigabitEthernet2",
                  "openconfig-network-instance:interface": "GigabitEthernet2",
                  "openconfig-network-instance:subinterface": "0"
                }
              }
            ]
          },
          "openconfig-network-instance:vlans": {},
          "openconfig-network-instance:vlan": []
        }
      ]
    }
  }
}
```

Device config:
[xe-65.txt](https://github.com/model-driven-devops/nso-oc-services/files/10914056/xe-65.txt)

**Comment by ygorelik** [comment]
Not reproducible after mdd package is recompiled.
