### ISSUE TITLE
illegal reference error when applying discovered network-instance service on XE device

### ISSUE THREAD

**Issue by ygorelik** [model-driven-devops/nso-oc-services#177]
This is regression test failure, which has appeared after merge to the latest code [7d9bea4](https://github.com/model-driven-devops/nso-oc-services/commit/7d9bea48583ef6a9063ae587f2fdb7a6404adfd6).

When applying discovered oc service network-instance on the XE device, I got the following error in mdd code:
```
<ERROR> 07-Mar-2023::13:16:40.188 mdd ncs-dp-59389-mdd:main:0-4-th-23128: - badly formatted or nonexistent path (8): Bad key "None" ("None" is not a valid value.) at: /devices/device/config/router/bgp
<ERROR> 07-Mar-2023::13:16:40.189 mdd ncs-dp-59389-mdd:main:0-4-th-23128: - Traceback (most recent call last):
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/application.py", line 766, in wrapper
    pl = fn(self, tctx, root, service, proplist)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/main.py", line 30, in cb_create
    check_xe_features(self)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_main.py", line 39, in check_xe_features
    xe_network_instances_program_service(oc_self)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_network_instances.py", line 32, in xe_network_instances_program_service
    xe_configure_protocols(self, service_table_connection_dict, instance_bgp_list)
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_network_instances.py", line 367, in xe_configure_protocols
    xe_bgp_global_program_service(self, bgp_instance[0], bgp_instance[1], bgp_instance[2])
  File "/Users/ygorelik/nso-oc-services/test-oc-services/state/packages-in-use/1/mdd/python/translation/openconfig_xe/xe_bgp.py", line 13, in xe_bgp_global_program_service
    if not self.root.devices.device[self.device_name].config.ios__router.bgp.exists(
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maagic.py", line 1260, in exists
    return self._backend._exists(self._path + keystr)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maagic.py", line 135, in _exists
    return self.exists(path)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maapi.py", line 1733, in proxy
    return real(self2.maapi, self2.th, *args, **kwargs)
  File "/Users/ygorelik/nso-5.8/src/ncs/pyapi/ncs/maapi.py", line 548, in exists
    return True if _tm.maapi.exists(self.msock, th, path) else False
_ncs.error.Error: badly formatted or nonexistent path (8): Bad key "None" ("None" is not a valid value.) at: /devices/device/config/router/bgp
```

Device config: 
[xe-config.txt](https://github.com/model-driven-devops/nso-oc-services/files/10914137/xe-config.txt)

Network-instance service config: 
[xe-ni-config.txt](https://github.com/model-driven-devops/nso-oc-services/files/10914145/xe-ni-config.txt)

**Comment by ygorelik** [comment]
Not reproducible after mdd package is recompiled.
